version: 1.2
workflows:
- name: PopulationSVSimulator
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SimulateHaplotypes.wdl
  testParameterFiles:
- name: PerformanceMatrices
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PerformanceMatrices.wdl
  testParameterFiles: