version: 1.2
workflows:
- name: SimulateHaplotypes
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SimulateHaplotypes.wdl
  testParameterFiles:
- name: JointCalling
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JointCalling.wdl
  testParameterFiles:
- name: PerformanceMatrices
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PerformanceMatrices.wdl
  testParameterFiles: