version: 1.2
workflows:
- name: SimulateHaplotypes
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SimulateHaplotypes.wdl
  testParameterFiles:
- name: JointCalling
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JointCalling.wdl
  testParameterFiles:
- name: AnnotateVCFs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/AnnotateVCFs.wdl
  testParameterFiles:
- name: PerformanceMatrices
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PerformanceMatrices.wdl
  testParameterFiles:
- name: ReadLengthDistribution
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/ReadLengthDistribution.wdl
  testParameterFiles:
- name: TriosCreateTruthVCFs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TriosCreateTruthVCFs.wdl
  testParameterFiles:
- name: TriosCreateTruthVCFs2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TriosCreateTruthVCFs2.wdl
  testParameterFiles:
- name: TriosPerformanceMatrices
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TriosPerformanceMatrices.wdl
  testParameterFiles: