#!/bin/bash
#
MODEL_DIR="../build_model/output"
POPULATION_NAME="ALL"
REFERENCE_FILE="./input/GRCh37_chr1.fa"
INSERTION_STRINGS_FILE="./input/union_170509_refalt_gt49bp.sort.INS.txt"
N_INSERTION_STRINGS="$(wc -l < ${INSERTION_STRINGS_FILE})"
ALLELE_FREQUENCY_THRESHOLD="0.01"
N_VARIANTS_FREQUENT="5000"
N_INDIVIDUALS="1000"   #"10000"
OUTPUT_DIR="./output"

java -Xmx10g -cp ./src SimulatePopulation ${MODEL_DIR} ${POPULATION_NAME} ${REFERENCE_FILE} ${INSERTION_STRINGS_FILE} ${N_INSERTION_STRINGS} ${ALLELE_FREQUENCY_THRESHOLD} ${N_VARIANTS_FREQUENT} ${N_INDIVIDUALS} ${OUTPUT_DIR}
